/*
PRACTICA 4 - "SELECTOR DE MENSAJES EN LCD" 
EQUIPO V 
8H1 - ELECTRONICA DIGITAL V
DAVID MADRID NAPOLES 17100201
JOSE GUILLERMO CALLEROS RODRIGUEZ 17100054
ERNESTO TORRES PEREZ 17100326
22/09/2020

DEBE DE MOSTRAR UN MENSAJE DIFERENTE DEPENDE DEL BOTON PRESIONADO, EL DISPLAY
INDICARA CUALES SON LOS BOTONES HABILITADOS, EN ESTE CASO LOS BOTONES SON
DEL UNO AL CINCO POR LO QUE MOSTRARA CINCO MENSAJES

*/
#INCLUDE <16F887.H>
#USE DELAY(CLOCK=4000000)
#FUSES INTRC_IO,NOWDT,NOPUT,NOMCLR,NOPROTECT,NOCPD,NOBROWNOUT
#FUSES NOIESO,NOFCMEN,NOLVP,NODEBUG,NOWRT,BORV21

#USE FAST_IO(A)
#USE FAST_IO(B)
#USE FAST_IO(C)
#USE FAST_IO(D)

#INCLUDE <LCD1.C>

INT I = 0, AUX = 0, CUENTA = 0;

VOID TECLADO (){ //SE ENCARGA DE DETECTAR PULSACIONES EN EL TECLADO
   AUX = 0XEF;
   CUENTA = 0; //LLEVARA LA CUENTA, DETECTANDO LA CUENTA PRESIONADO
   FOR(I=0;I<4;I++){//EN CADA ITERACION REVISA UNA FILA DIFERENTE
         
      AUX=AUX>>1; //DESPLAZA UN CERO A LA DERECHA
      OUTPUT_A((INPUT_A()&0XF0)|(AUX&0X0F));
         
      IF(INPUT(PIN_A7)==0) //REVISDA ESTADO COLUMNA A7
      BREAK;
      CUENTA++;
      IF(INPUT(PIN_A6)==0) //REVISDA ESTADO COLUMNA A6
      BREAK;
      CUENTA++;
      IF(INPUT(PIN_A5)==0) //REVISDA ESTADO COLUMNA A5
      BREAK;
      CUENTA++;
      IF(INPUT(PIN_A4)==0) //REVISDA ESTADO COLUMNA A4
      BREAK;
      CUENTA++;
         
      DELAY_MS(20); //TIEMPO DE ESPERA NECESARIO PARA DETECTAR CAMBIOS
   }
}
VOID MENU () { //SE ENCARGA DE MOSTRAR LAS OPCIONES DEL MENU
//ESPERA MEDIO SEGUNDO POR OPCION
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC, "1- ESCUELA         \n                ");
   DELAY_MS(500);
               
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC, "2- CARRERA         \n                ");
   DELAY_MS(500);
     
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC, "3- MATERIA         \n                ");
   DELAY_MS(500);
      
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC, "4- NOMBRES Y    \nREGISTROS       ");
   DELAY_MS(500);
                 
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC, "5- N. Y NOMBRE  \nDE LA PRACTICA  ");
   DELAY_MS(500);
}
VOID RES (){ //SE ENCARGA DE RESPONDER A LA PETICION DEL MENU
   SWITCH (CUENTA){
      CASE 0: //RESPUESTA TECLA 1
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC, "CETI           \nCOLOMOS         ");
      BREAK;
               
      CASE 1: //RESPUESTA TECLA 2
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC, "TGO CONTROL     \nAUTOMATICO        ");
      BREAK;
               
      CASE 2: //RESPUESTA TECLA 3
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC, "ELECTRONICA       \nDIGITAL V         ");
      BREAK;
               
      CASE 4: //RESPUESTA TECLA 4
      FOR(I = 0; I <= 2; I++){ // EN CADA ITERACION MUESTRA EL R Y N DE UN ALM
         SWITCH (I){
            CASE 0:
            LCD_GOTOXY(1,1);
            PRINTF(LCD_PUTC, "DAVID MADRID     \n17100201            ");
            BREAK;
               
            CASE 1:
            LCD_GOTOXY(1,1);
            PRINTF(LCD_PUTC, "JOSE CALLEROS     \n17100054          ");
            BREAK;
                     
            CASE 2:
            LCD_GOTOXY(1,1);
            PRINTF(LCD_PUTC, "ERNESTO TORRES     \n17100326         ");
            BREAK;
            }
         DELAY_MS(500);
         }
      BREAK;
               
      CASE 5: //RESPUESTA TECLA 5
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC, "SELECTOR DE SMS \nEN LCD PRACT 4         ");
      BREAK;
               
      DEFAULT: //OPCION INVALIDA
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC, "     OPCION     \n    INVALIDA           ");
   }
}


VOID MAIN (){ //FUNCION PRINCIPAL

   SET_TRIS_A(0XF0); //DECLARAR PUERTOS
   OUTPUT_A(INPUT_A()&0XF0); //LIMPIAR BITS DE SALIDA
   LCD_INIT(); //INICIAR LCD
   
   WHILE (TRUE){ //CICLO INFINITO
      
      MENU (); //MUESTRA MENU
      
      TECLADO (); //LEE EL TECLADO
      
      IF(CUENTA<16){ //SI SE PRESIONA UNA TECLA
      
         RES ();//DA UNA RESPUESTA A LA TECLA
            
         WHILE(CUENTA<16){ //PRESIONADA LA TECLA
            TECLADO (); //SIGUE DETECTANDOLA Y RESPONDE SIN MOSTAR EL MENU
         }
      }
   } 
}
